### ISSUE TITLE
Add honors and web-only fields to Section

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#120]
Need to figure out what fields in the course-scraping data denotes an honors or web class, and update the Section models accordingly.

This way, when we send the course data to the frontend, the frontend can quickly filter honors-only and/or web-only section.

**Comment by gannonprudhomme** [comment]
Does this still need to be done? @ryan-conn

**Comment by ryan-conn** [comment]
No, I added them in the `backend/api/scaper/tests` branch
