### ISSUE TITLE
Setup ESLint for Typescript

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#13]
Need to configure ESLint for Typescript so that we can have a standard coding convention & catch basic syntax errors

Possibly integrate it into VSCode so that it runs on save? Might be able to do it with the ESLint VSCode extension

**Comment by firejake308** [comment]
Do we want to enforce a certain code style? e.g. AirBnb, Standard, or Google?

**Comment by firejake308** [comment]
I've also decided to run the linter on save rather than on type so that it won't complain just because my typing speed is under 50 wpm. If anyone disagrees with that, we can change it.

**Comment by gannonprudhomme** [comment]
Should be fine for now. Is Airbnb your preference? 

Also, are these configurations for just Javascript, or Typescript as well?

**Comment by firejake308** [comment]
Airbnb is the most popular one, according to some quick googling. They should apply to both JS and TS files
