### ISSUE TITLE
Setup React & Typescript testing framework

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#14]
Need to determine what testing framework we'd like to use for the frontend (i.e. Mocha and Chai), and set it up for use in the project

Also possibly integrate it into VSCode so that they run on save?

**Comment by gannonprudhomme** [comment]
Most likely will use Jest as our overall testing framework. 

Do you think we should do UI testing? @firejake308 
As in actually automating clicking/navigating our components and making sure they react(lol) correctly.

Thinking about using https://testing-library.com/docs/react-testing-library/example-intro in that regard

**Comment by firejake308** [comment]
I think that with this many people working on a project, it could easily become difficult to keep track of what each piece of code is doing, so testing is a good idea to ensure that no one accidentally screws up anyone else's code. And Jest with testing-library is the letup that Facebook recommended, so yeah, sounds good.

**Comment by gannonprudhomme** [comment]
I'm pretty busy with backend stuff and am not sure when I can get to this, would you mind working on this when you get the chance @firejake308 ?
