### ISSUE TITLE
Setup Redux

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#18]
Need to add an outline of Redux on the frontend, so the "skeleton" is there once we begin the project.

**Comment by firejake308** [comment]
Heads up, Redux adds quite a bit of boilerplate, so frontend team members may want to check out the [tutorial](https://react-redux.js.org/introduction/basic-tutorial) to get a feel for what everything is doing

**Comment by firejake308** [comment]
Never mind. That tutorial was way too complicated. Try [this one](https://redux.js.org/basics/basic-tutorial) instead
