### ISSUE TITLE
Create prototype designs

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#20]
We need to create the prototype of the designs of the website, as having one will help us get a clearer image of what we need to work on/add first.

**Comment by gannonprudhomme** [comment]
Will assign all of the frontend team once they all join

**Comment by btgathright** [comment]
Hey, I saw you assigned me and unassigned me to #20. Am I working on
frontend or backend? I don't have a preference, I'm willing to learn either
language so whichever team needs more help.

**Comment by gannonprudhomme** [comment]
Yeah 'twas an accident. Right now we'd like you on backend as we already have Adel, Scott & Chris on frontend, and only Carlos and a UT friend of mine Lucas on backend. However it should be pretty fluid/people can work on whatever they want, its just really for like organizational purposes in the short term right now

**Comment by btgathright** [comment]
Alright, I am currently trying to issue the Department model from zenhub
but haven't used it before so I'm not sure if I just created that issue
properly.

**Comment by gannonprudhomme** [comment]
You don't need to create the issue as I already have, just need to assign yourself to it. It's #24

**Comment by btgathright** [comment]
ZenHub keeps throwing an error when trying to assign myself. I'm going to
start working on it and try to assign myself again in a bit.

**Comment by gannonprudhomme** [comment]
That's really weird. You should just be able to go to the issue directly in GitHub(as ZenHub just uses GitHub's issue system) and assign yourself that way.

**Comment by firejake308** [comment]
Aight, I think I've got the basic prototype down for the mobile layout at least. Have to expand it a little, add a few fields on desktop, but I'm open to feedback on my design now.
