### ISSUE TITLE
Implement course scraping

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#44]
Need to implement course scraping, which will also include scraping/parsing for `Instructor`, `Section` and `Meeting`. 

To begin working on one of the issues(`parse_section`, `parse_course`, etc), first checkout `backend/course-scraping` then make a branch off of it. Then add commits to it, and once you're done make a pull request to merge your branch into `backend/course-scraping`.

**Comment by ryan-conn** [comment]
When running async functions in commands (such as `scrape-courses`), we'll need to do the following in order to run them synchronously:
```
# in scrape-courses.py (function to synchronously run async):
def run_async(function, args):
    loop = asyncio.get_event_loop()
    tasks = [asyncio.ensure_future(function(args))]
    return loop.run_until_complete(asyncio.wait(tasks))
```
And in `handle(self, *args, **options)`, put the following to get the data:
```
depts = ["CSCE", "MATH", "CHEM"]
banner = BannerRequests("201931")
data = run_async(banner.search, depts)
```

**Comment by gannonprudhomme** [comment]
Just by the way @ThatJuanGuy, I updated the description of this issue to reflect what we're doing instead of that `JSESSIONID` cookie stuff. It turns out I was completely wrong about needing to directly deal with cookies like that, as told to me by this random internet god on my other repo [here](https://github.com/gannonprudhomme/AutoScheduler/issues/10)
