### ISSUE TITLE
Implement MeetingCard

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Automatic-Aggie-Scheduler#54]
Hello, my frontend friends! I have written some tests for your first React component, `<MeetingCard />` and created a skeleton file for you to fill. Basically, I want you to learn about functional components in React, then make one that creates a MeetingCard. The component takes in a meeting as its props and it should render a card-like shape that has the subject and course number of that meeting. Once you've written your component, you can see the result for yourself by replacing `<Empty />` with `<MeetingCard meeting={insert dummy meeting variable here} />` in `App.tsx`, and if it looks good to you, run `npm run lint` to clean up your code, then `npm run test` to see if it works. If the tests pass, go ahead and commit it, and i'll check over your code. We'll be working on the `frontend/meeting` branch, so to get started, just assign yourself in GitHub and drag this issue into the Todo section in ZenHub. GLHF!

**Comment by gannonprudhomme** [comment]
If this is already implemented for them to work on and assumingly doesn't break anything, I you might as well make a PR to merge `frontend/meeting` to `frontend/master`, that way we have less to review when they do the PR with their changes.

**Comment by firejake308** [comment]
Okay, I'll make that PR after we go over `types.ts`

**Comment by gannonprudhomme** [comment]
See [Material-UI](https://material-ui.com/) for what components we have to work with.

**Comment by firejake308** [comment]
Good news, everyone! I discovered that if you extend `React.PureComponent`, you can write a stateless class component. This will hopefully make it easier for @scott-carrion because the class component syntax is more similar to the OOP that most people have experience with. If you have any questions, Scott, feel free to message me on Slack or comment on this issue.

**Comment by firejake308** [comment]
By the way, I implemented the changes y'all requested in #57 and merged the tests into your branch for this

**Comment by firejake308** [comment]
The meeting card has been merged into `frontend/schedule`. Marking as closed.
