### ISSUE TITLE
Implement parse_course function

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Automatic-Aggie-Scheduler#62]
`parse_course` is the main function for scraping courses, and needs to be filled in before any of the other `parse_` functions in `scrape_courses.py`. This function should save Course objects into the database, and call `parse_section` and `parse_instructors` with the relevant parts of the `course` object, which will save the rest of the course models (Section, Meeting, and Instructor) into the database.

See #44

**Comment by gannonprudhomme** [comment]
@ThatJuanGuy are you working on this on your own branch?
