### ISSUE TITLE
Implement css and font loading for Webpack/React

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#73]
Need to look into and implement how to do css and font loading for Webpack.

[This article](https://medium.com/@dmitrynozhenko/9-ways-to-implement-css-in-react-js-ccea4d543aa3) outlines a few ways for how to go about it. I was mainly looking at the first one(Standard css) and the third(css modules), but wasn't sure which was the best. 

Likewise for fonts, we'll either need to use [url-loader](https://www.npmjs.com/package/url-loader) or [file-loader](https://www.npmjs.com/package/file-loader), depending on if we want to use fonts from a CDN, or if we want to download the fonts locally. If we do want to download the fonts locally, we can use [typefaces](https://github.com/KyleAMathews/typefaces). 

This should also include setting the fonts in the Theme for Material-UI, which you can read more about [here](https://material-ui.com/customization/typography/).

**Comment by gannonprudhomme** [comment]
Any thoughts on doing standard css vs css modules @firejake308 ?

**Comment by firejake308** [comment]
If you look at my `frontend/schedule branch, you'll see that I've been using css-loader and style-loader with regular CSS files that you can just import into your JS files. I find that to be the most intuitive way to write CSS. I just looked up CSS modules, and I definitely want our CSS to be local-scoped by default, so modules will be a good way to ensure that styles for one component don't mess up styles for another component

**Comment by firejake308** [comment]
Also, I can take this one because I have half of it done anyway, so it's just a matter of pasting that code into a new branch

**Comment by gannonprudhomme** [comment]
Sounds good, go for it

**Comment by gannonprudhomme** [comment]
Closing, per #88
